/**
 * TripPDF — Traveloop PDF export utility
 * Generates a printable HTML page for the trip itinerary and triggers the browser print dialog.
 */

interface DownloadPDFOptions {
  trip: any
  days: any[]
  places: any[]
  assignments: any
  categories?: any[]
  dayNotes?: any[]
  reservations?: any[]
  t: (key: string, params?: any) => string
  locale?: string
}

export async function downloadTripPDF(opts: DownloadPDFOptions): Promise<void> {
  const { trip, days, places, t } = opts

  const placeMap: Record<number, any> = {}
  for (const p of places) placeMap[p.id] = p

  const formatDate = (d: string) =>
    d ? new Date(d + 'T00:00:00Z').toLocaleDateString(opts.locale || 'en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC',
    }) : ''

  const dayRows = days.map((day: any) => {
    const dayPlaces = (opts.assignments?.[day.id] || [])
      .map((a: any) => placeMap[a.place?.id] || a.place)
      .filter(Boolean)

    const placeList = dayPlaces.length
      ? dayPlaces.map((p: any) => `<li>${p.name || ''}${p.address ? ` — ${p.address}` : ''}</li>`).join('')
      : '<li style="color:#9ca3af">No places planned</li>'

    return `
      <div style="margin-bottom:28px;page-break-inside:avoid">
        <h3 style="margin:0 0 8px;font-size:15px;font-weight:700;color:#0ea5e9;border-bottom:1px solid #e5e7eb;padding-bottom:6px">
          Day ${day.day_number || ''}${day.date ? ` — ${formatDate(day.date)}` : ''}
          ${day.title ? `<span style="font-weight:400;color:#6b7280;font-size:13px"> · ${day.title}</span>` : ''}
        </h3>
        <ul style="margin:0;padding-left:20px;font-size:13px;line-height:1.7">${placeList}</ul>
      </div>`
  }).join('')

  const html = `
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8"/>
      <title>Traveloop — ${trip?.title || 'Trip'}</title>
      <style>
        * { box-sizing: border-box; }
        body { font-family: Arial, sans-serif; color: #111827; padding: 40px; max-width: 800px; margin: 0 auto; }
        h1  { font-size: 26px; font-weight: 800; color: #0ea5e9; margin: 0 0 4px; }
        .meta { font-size: 13px; color: #6b7280; margin-bottom: 32px; }
        @media print { body { padding: 20px } }
      </style>
    </head>
    <body>
      <h1>${trip?.title || 'Trip Itinerary'}</h1>
      <p class="meta">
        ${trip?.start_date ? `${formatDate(trip.start_date)} → ${formatDate(trip.end_date)}` : ''}
        ${trip?.description ? ` &nbsp;·&nbsp; ${trip.description}` : ''}
        &nbsp;·&nbsp; Generated by <strong>Traveloop</strong> on ${new Date().toLocaleDateString()}
      </p>
      ${dayRows || '<p style="color:#9ca3af">No days in this trip.</p>'}
    </body>
    </html>`

  const w = window.open('', '_blank', 'width=900,height=700')
  if (!w) {
    alert('Please allow popups to export the PDF.')
    return
  }
  w.document.open()
  w.document.write(html)
  w.document.close()
  setTimeout(() => { w.focus(); w.print() }, 400)
}
// Traveloop – Travel Planning Platform 2026
